# Generated by Django 4.2.1 on 2023-06-02 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=32, verbose_name='Odnośnik')),
                ('opisc', models.TextField(blank=True, max_length=300, verbose_name='Opis Kategorii')),
            ],
            options={
                'verbose_name_plural': 'Kategorie',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=32, verbose_name='Odnośnik')),
                ('opist', models.TextField(blank=True, max_length=300, verbose_name='Opis Tagu')),
            ],
            options={
                'verbose_name_plural': 'Tagi',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=62, verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=32, verbose_name='Odnośnik')),
                ('body', models.TextField(verbose_name='Treść')),
                ('pub_date', models.DateTimeField(verbose_name='Data Publikacji')),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='active', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Image Only: JPG, JPEG, PNG, WebP.', null=True, upload_to='static/', verbose_name='Obraz')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='Kategoria')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Strona')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Tagi')),
            ],
            options={
                'verbose_name_plural': 'Artykuły',
                'ordering': ('-pub_date',),
            },
        ),
    ]
